# NUMPY

NumPy is a Python library that can be used for scientific calculations and it is used as a tool for linear algebra operations.

# 1.1 ARRAY CREATION

We can create a NumPy array by passing a  python list to it using 'np.array()'

* 1-D Array
* 2-D Array
* 3-D Array
* Attributes
    * ndim
    * shape
    * size
    * dtype
    * itemsize
    * databuffer
* Axis
* zeros
* ones
* arange
* linspace
* full
* eye
* empty
* rand and randn


## 1D Array

In [1]:
import numpy as np   #first import the numpy library
a = np.array([1,2,3])  #creation of 1d array
print(a)

[1 2 3]


## 2D Array

In [2]:
b=np.array([(1,2,3),(4,5,6)])  #creation of 2d array
print(b)

[[1 2 3]
 [4 5 6]]


## 3D Array(N-Dimensional Array)

In [3]:
c = np.array( [[[0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [3, 4, 5]],
                [[10, 11, 12],              #N-Dimensional array
                [13, 14, 15]]])
print(c)

[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]]


### some of the important attributes to be noted are:

i)ndim ---No.of dimensions(axes) of array

ii)shape---Dimensions of the array

iii)size---No.of elements in array

iv)dtype---Describes the type of elements present in an array

v)itemsize---Tells about the size in bytes of each element in array

vi)data---The buffer object pointing to the start of the array’s data.

data,dtype will be discussed in later sections

### for 1-D array

In [4]:
a

array([1, 2, 3])

In [5]:
a.shape 

(3,)

In [6]:
len(a)   #length of the array

3

In [7]:
a.ndim   

1

In [8]:
a.size 

3

In [9]:
a.itemsize

4

In [10]:
a.data 

### for 2-D array

In [11]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b.shape  

(2, 3)

In [13]:
len(b)  

2

In [14]:
b.ndim 

2

In [15]:
b.size 

6

In [16]:
b.itemsize 

4

In [17]:
b.data

### for N-D array

In [18]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [19]:
c.shape 

(2, 2, 3)

In [20]:
len(c)  #length of the array

2

In [21]:
c.ndim  

3

In [22]:
c.size 

12

In [23]:
c.itemsize

4

In [24]:
c.data

## axis

axis=0 -->Direction along rows

axis=1 -->Direction along columns

In [25]:
import numpy as np
x=np.array([(1,7,3),(4,5,6)])  #here no.of rows=2,no.of cols=3
print(x)

[[1 7 3]
 [4 5 6]]


In [26]:
##axis=0
x.sum(axis=0) #sum is calculated along the 2rows 

array([ 5, 12,  9])

In [27]:
x.min(axis=0)  #minimum value is taken along 2rows

array([1, 5, 3])

In [28]:
x.max(axis=0)  #maximum value is taken along 2 rows

array([4, 7, 6])

In [29]:
##axis=1
x.sum(axis=1) #sum is calculated along the 3columns

array([11, 15])

In [30]:
x.min(axis=1) #minimum value is taken along 3 columns

array([1, 4])

In [31]:
x.max(axis=1) #maximum value is taken along 3 columns

array([7, 6])

## zeros

The `zeros` function creates an array containing any number of zeros:

In [32]:
e=np.zeros((2))
print(e)

[0. 0.]


In [33]:
e.ndim

1

It's just as easy to create a 2D array (ie. a matrix) by providing a tuple with the desired number of rows and columns. For example, here's a 3x4 matrix:

In [34]:
f=np.zeros((3,4))
f

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Note

* In NumPy, each dimension is called an **axis**.

* The number of axes is called the **rank**.
   * For example, the above 3x4 matrix is an array of rank 2 (it is 2-dimensional).
   * The first axis has length 3, the second has length 4.
* An array's list of axis lengths is called the **shape** of the array.
    * For example, the above matrix's shape is `(3, 4)`.
    * The rank is equal to the shape's length.
* The **size** of an array is the total number of elements, which is the product of all axis lengths (eg. 3*4=12)

In [35]:
f.ndim

2

In [36]:
f.size

12

You can also create an N-dimensional array of arbitrary rank. For example, here's a 3D array (rank=3), with shape `(2,3,4)`:

In [37]:
g=np.zeros((2,3,4))
print(g)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [38]:
g.ndim

3

## ones

The `ones` function creates an array containing any number of ones:

In [39]:
e=np.ones((2))
print(e)

[1. 1.]


In [40]:
e.ndim

1

In [41]:
f=np.ones((2,3))
f

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
f.ndim

2

In [43]:
g=np.ones((2,3,4))
g

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [44]:
g.ndim

3

## arange

we can create an `ndarray` using NumPy's `arange` function, which is similar to python's built-in `range` function:

In [45]:
x=np.arange(1, 5)
print(x)

[1 2 3 4]


In [46]:
y=np.arange(1.0, 5.0) #works with float type
y

array([1., 2., 3., 4.])

In [47]:
z=np.arange(1, 5, 0.5) #we can provide the step parameter
z

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

However, when dealing with floats, the exact number of elements in the array is not always predictible. For example, consider this:

In [48]:
import numpy as np
print(np.arange(0, 5/3, 1/3)) # depending on floating point errors, the max value is 4/3 or 5/3.
print(np.arange(0, 5/3, 0.333333333))
print(np.arange(0, 5/3, 0.333333334))
print(np.arange(0, 100, 11))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.         0.33333333 0.66666667 1.         1.33333334]
[ 0 11 22 33 44 55 66 77 88 99]


## linspace

For this reason, it is generally preferable to use the `linspace` function instead of `arange` when working with floats. The `linspace` function returns an array containing a specific number of points evenly distributed between two values (note that the maximum value is *included*, contrary to `arange`):

In [49]:
np.linspace(0, 5/3, 6)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

In [50]:
np.linspace(0, 2, 6) #no.of samples=6 taken from range 0 to 2

array([0. , 0.4, 0.8, 1.2, 1.6, 2. ])

In [51]:
print(np.linspace(0, 100, 11))

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


## full

Creates an array of the given shape initialized with the given value. Here's a 3x4 matrix full of `π`.

In [52]:
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

## eye

In [53]:
np.eye(2,2) #identity matrix

array([[1., 0.],
       [0., 1.]])

## empty

An uninitialized 2x3 array (its content is not predictable, as it is whatever is in memory at that point):

In [54]:
np.empty((3,2))

array([[0. , 0.4],
       [0.8, 1.2],
       [1.6, 2. ]])

## rand and randn
A number of functions are available in NumPy's `random` module to create `ndarray`s initialized with random values.
For example, here is a 3x4 matrix initialized with random floats between 0 and 1 (uniform distribution):

In [55]:
np.random.rand(3,4)

array([[0.77085025, 0.58894704, 0.31839515, 0.04188592],
       [0.35613332, 0.68509746, 0.3191923 , 0.19396171],
       [0.61750943, 0.78343454, 0.44373316, 0.7739878 ]])

In [56]:
np.random.randn(3,4)

array([[-0.75379367, -1.23128138, -0.5586747 ,  0.42597764],
       [ 1.07212971,  2.10052468,  1.26374424,  0.91426936],
       [ 0.29711459,  1.17699024, -0.29315236, -0.79808705]])

## dtype

NumPy's ndarrays are also efficient in part because all their elements must have the same type (usually numbers). You can check what the data type is by looking at the 'dtype' attribute.

some of the datatypes are:

a)int
b)float
c)bool
d)complex

In [57]:
x=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
x.dtype

dtype('int32')

In [59]:
y=np.array([(1.1,2.1,3.0),(4.5,5.7,6.8),(7,8.9,9)])
y

array([[1.1, 2.1, 3. ],
       [4.5, 5.7, 6.8],
       [7. , 8.9, 9. ]])

In [60]:
y.dtype

dtype('float64')

In [61]:
x = np.arange(1, 5)
print(x.dtype, x)

int32 [1 2 3 4]


In [62]:
y = np.arange(1.0, 5.0)
print(y.dtype, y)

float64 [1. 2. 3. 4.]


Instead of letting NumPy guess what data type to use, you can set it explicitly when creating an array by setting the dtype parameter:

In [63]:
z = np.arange(1, 5, dtype=np.complex64)
print(z.dtype, z)

complex64 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


Available data types include int8, int16, int32, int64, uint8|16|32|64, float16|32|64 and complex64|128. Check out the documentation for the full list.

In [64]:
h=np.array([(1,0),(0,0)],bool)  #1-->True, 0-->False
h

array([[ True, False],
       [False, False]])

## databuffer

An array's data is actually stored in memory as a flat (one dimensional) byte buffer. It is available *via* the `data` attribute (you will rarely need it, though).

In [65]:
f = np.array([[1,2],[1000, 2000]], dtype=np.int32)
f.data