# 1.2 OPERATIONS ON NUMPY ARRAY

* Arthimetic operations
* Conditional operations
* Set operations

## ARTHIMETIC OPERATIONS

All the usual arithmetic operators (`+`, `-`, `*`, `/`, `//`, `**`, etc.) can be used with `ndarray`s. They apply *elementwise*:

In [2]:
import numpy as np
a = np.array([14, 23, 32, 41])
b = np.array([5,  4,  3,  2])
print("a + b  =", a + b)
print("a - b  =", a - b)
print("a * b  =", a * b)
print("a / b  =", a / b)
print("a // b  =", a // b)
print("a % b  =", a % b)
print("a ** b =", a ** b)

a + b  = [19 27 35 43]
a - b  = [ 9 19 29 39]
a * b  = [70 92 96 82]
a / b  = [ 2.8         5.75       10.66666667 20.5       ]
a // b  = [ 2  5 10 20]
a % b  = [4 3 2 1]
a ** b = [537824 279841  32768   1681]


Note: Multiplication is *not* a matrix multiplication.

## CONDITIONAL OPERATIONS

The conditional operators also apply elementwise:

In [3]:
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

array([False,  True,  True, False])

In [4]:
m[m < 25]

array([20, -5])

In [5]:
m[m > 25]

array([30, 40])

In [6]:
a=np.array([1,0,1,0])
b=np.array([1,1,1,1])
a==b

array([ True, False,  True, False])

## SET OPERATIONS

In [7]:
import numpy as np
 
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[2, 1, 0], [4, 3, 6]])
 
# Find the union of two arrays.
print(np.union1d(array1, array2))
 
# Find the intersection of two arrays.
print(np.intersect1d(array1, array2))
 
# Find the set difference of two arrays.
print(np.setdiff1d(array1, array2))

[0 1 2 3 4 5 6]
[1 2 3 4 6]
[5]
