# 1.3 MATHEMATICAL AND STATISTICAL FUNCTIONS

In [1]:
##Basic mathematical functions
import numpy as np
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print(a)
print("min =", a.min())
print("max =",a.max())
print("sum =",a.sum())
print("prod =",a.prod())
print("cumsum =",a.cumsum())
print("mean =",a.mean())

[[-2.5  3.1  7. ]
 [10.  11.  12. ]]
min = -2.5
max = 12.0
sum = 40.6
prod = -71610.0
cumsum = [-2.5  0.6  7.6 17.6 28.6 40.6]
mean = 6.766666666666667


Note: This computes the mean of all elements in the `ndarray`, regardless of its shape.


These functions accept an optional argument `axis` which lets you ask for the operation to be performed on elements along the given axis. For example:

In [2]:
b=np.arange(24).reshape(2,3,4)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [3]:
b.sum(axis=0)  # sum across matrices

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [4]:
b.sum(axis=1)  # sum across rows

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

You can also sum over multiple axes:

In [5]:
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [6]:
b.sum(axis=(0,2))  # sum across columns of matrices

array([ 60,  92, 124])

In [7]:
##basic statistical functions

In [8]:
for func in (a.mean, a.std, a.var):
    print(func.__name__, "=", func())

mean = 6.766666666666667
std = 5.084835843520964
var = 25.855555555555554
