# 1.5 ARRAY MANIPULATION


* Stacking together different arrays
    * vstack
    * hstack
    * concatenate
    * stack
* Splitting Arrays
    * vsplit
    * hsplit
* Changing the shape of the Array
    * ravel
    * reshape
    * swapaxes
    * Transpose of an array


## Stacking Arrays

* vstack
* hstack
* concatenate
* stack

It is often useful to stack together different arrays. NumPy offers several functions to do just that. Let's start by creating a few arrays.

In [1]:
import numpy as np
q1 = np.full((3,4), 1.0)
print(q1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [2]:
q2 = np.full((4,4), 2.0)
print(q2)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [3]:
q3 = np.full((3,4), 3.0)
print(q3)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


### vstack

Now let's stack them vertically using `vstack`:

In [4]:
q4 = np.vstack((q1, q2, q3))
print(q4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [5]:
q4.shape

(10, 4)

This was possible because q1, q2 and q3 all have the same shape (except for the vertical axis, but that's ok since we are stacking on that axis).

### hstack
We can also stack arrays horizontally using `hstack`:

In [6]:
q5 = np.hstack((q1, q3))
print(q5)

[[1. 1. 1. 1. 3. 3. 3. 3.]
 [1. 1. 1. 1. 3. 3. 3. 3.]
 [1. 1. 1. 1. 3. 3. 3. 3.]]


In [7]:
q5.shape

(3, 8)

This is possible because q1 and q3 both have 3 rows. But since q2 has 4 rows, it cannot be stacked horizontally with q1 and q3:

In [8]:
try:
    q5 = np.hstack((q1, q2, q3))
except ValueError as e:
    print(e)

all the input array dimensions except for the concatenation axis must match exactly


### concatenate

The `concatenate` function stacks arrays along any given existing axis.

In [9]:
q7 = np.concatenate((q1, q2, q3), axis=0)  # Equivalent to vstack
print(q7)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [10]:
q7.shape

(10, 4)

### stack
The `stack` function stacks arrays along a new axis. All arrays have to have the same shape.

In [11]:
q8 = np.stack((q1, q3))
print(q8)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]]


In [12]:
q8.shape

(2, 3, 4)

## Splitting arrays

* vsplit
* hsplit

### vsplit

Splitting is the opposite of stacking. For example, let's use the `vsplit` function to split a matrix vertically.

First let's create a 6x4 matrix:

In [13]:
r = np.arange(24).reshape(6,4)
print(r)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


Now let's split it in three equal parts, vertically:

In [14]:
r1, r2, r3 = np.vsplit(r, 3)
print(r1)

[[0 1 2 3]
 [4 5 6 7]]


In [15]:
print(r2)

[[ 8  9 10 11]
 [12 13 14 15]]


In [16]:
print(r3)

[[16 17 18 19]
 [20 21 22 23]]


There is also a `split` function which splits an array along any given axis. Calling `vsplit` is equivalent to calling `split` with `axis=0`. There is also an `hsplit` function, equivalent to calling `split` with `axis=1`:

### hsplit

In [17]:
r4, r5 = np.hsplit(r, 2)
print(r4)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]
 [20 21]]


In [18]:
print(r5)

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]
 [22 23]]


## Changing the shape of the array

* shape
* reshape
* ravel
* Transpose
* swapaxes

### shape

Changing the shape of an `ndarray` is as simple as setting its `shape` attribute. However, the array's size must remain the same.

In [19]:
g = np.arange(24)
print(g)
print("Rank:", g.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Rank: 1


In [20]:
g.shape = (6, 4)
print(g)
print("Rank:", g.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Rank: 2


In [21]:
g.shape = (2, 3, 4)
print(g)
print("Rank:", g.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Rank: 3


### reshape

The `reshape` function returns a new `ndarray` object pointing at the *same* data. This means that modifying one array will also modify the other.

In [22]:
g2 = g.reshape(4,6)
print(g2)
print("Rank:", g2.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Rank: 2


Set item at row 1, col 2 to 999 (more about indexing below).

In [23]:
g2[1, 2] = 999
print(g2)

[[  0   1   2   3   4   5]
 [  6   7 999   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]]


The corresponding element in `g` has been modified.

In [24]:
print(g)

[[[  0   1   2   3]
  [  4   5   6   7]
  [999   9  10  11]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]]]


### ravel
Finally, the `ravel` function returns a new one-dimensional `ndarray` that also points to the same data:

In [25]:
g.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7, 999,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

### Transpose
The `transpose` method creates a new view on an `ndarray`'s data, with axes permuted in the given order.

For example, let's create a 3D array:

In [26]:
t = np.arange(24).reshape(4,2,3)
print(t)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


Now let's create an `ndarray` such that the axes `0, 1, 2` (depth, height, width) are re-ordered to `1, 2, 0` (depth→width, height→depth, width→height):

In [27]:
t1 = t.transpose((1,2,0))
print(t1)

[[[ 0  6 12 18]
  [ 1  7 13 19]
  [ 2  8 14 20]]

 [[ 3  9 15 21]
  [ 4 10 16 22]
  [ 5 11 17 23]]]


In [28]:
t1.shape

(2, 3, 4)

In [29]:
t2 = t.transpose()  # equivalent to t.transpose((2, 1, 0))
print(t2)

[[[ 0  6 12 18]
  [ 3  9 15 21]]

 [[ 1  7 13 19]
  [ 4 10 16 22]]

 [[ 2  8 14 20]
  [ 5 11 17 23]]]


By default, `transpose` reverses the order of the dimensions:

### Swapaxes
NumPy provides a convenience function `swapaxes` to swap two axes. For example, let's create a new view of `t` with depth and height swapped:

In [30]:
t3 = t.swapaxes(0,1)  # equivalent to t.transpose((1, 0, 2))
print(t3)

[[[ 0  1  2]
  [ 6  7  8]
  [12 13 14]
  [18 19 20]]

 [[ 3  4  5]
  [ 9 10 11]
  [15 16 17]
  [21 22 23]]]


In [31]:
t3.shape

(2, 4, 3)